USE SEMESTRAL;

SELECT * FROM PROVINCE;

-- CREA SP GET PROVINCE

CREATE PROCEDURE SP_PROVINCE_GET
AS
BEGIN
	SELECT ID_PROVINCE, PRO_NAME FROM PROVINCE;
END;

EXEC SP_PROVINCE_GET;

-- crea tabla usuarios

CREATE TABLE USERS(
ID_USER INT IDENTITY(1,1) PRIMARY KEY,
COD_USER VARCHAR(10) NOT NULL,
USE_NAME VARCHAR(50) NOT NULL,
USE_LASTNAME VARCHAR(50) NOT NULL,
USE_EMAIL VARCHAR(50) NOT NULL,
USE_PHONE VARCHAR(50) NOT NULL,
USE_ADDRESS VARCHAR(50) NOT NULL,
USE_SALARIE DECIMAL(10,2) NOT NULL,
ID_DITRICT INT NOT NULL,
ID_STATE INT NOT NULL,
TYPE_USER VARCHAR(50) NOT NULL)
 
 -- ADD COLUMNS
 ALTER TABLE USERS ADD ID_PROVINCE INT NULL;
 ALTER TABLE USERS ADD USE_IDENT VARCHAR(50) NULL;

 --ALTER TABLE USERS ALTER COLUMN ID_PROVINCE INT NOT NULL;
 -- CREATESP GET USERS
 CREATE PROCEDURE SP_USERS_GET_BY_ID
 @COD_USER VARCHAR(10),
 @TYPE_USER VARCHAR(50)
AS
BEGIN
	SELECT ID_USER
		   , COD_USER 
		   , USE_NAME 
		   , USE_LASTNAME
		   , USE_EMAIL 
		   , USE_PHONE 
		   , USE_ADDRESS 
		   , USE_SALARIE 
		   , ID_DITRICT 
		   , ID_STATE 
	FROM USERS
	WHERE TYPE_USER = @TYPE_USER
	AND (COD_USER = @COD_USER);
END;


INSERT INTO USERS (COD_USER 
		   , USE_NAME 
		   , USE_LASTNAME
		   , USE_EMAIL 
		   , USE_PHONE 
		   , USE_ADDRESS 
		   , USE_SALARIE 
		   , ID_DITRICT 
		   , ID_STATE
		   , TYPE_USER)
		   VALUES ('1001', 'JUAN', 'PEREZ', 'JPERES@UNIVERSIDAD.COM', '6421-2031', 'Panama, Panamá', 1000, 1, 1, 'Profesor')